# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1

commands:
  install_docker_client:
    description: "Install Docker client"
    steps:
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
  checkout_ruby_trunk:
    description: "Checkout Ruby trunk"
    steps:
      - restore_cache:
          keys:
            - ruby-trunk
      - run:
          command: |
            if test -f tmp/ruby/configure.ac; then
              cd tmp/ruby
              git pull --rebase
            else
              mkdir -p tmp
              git clone https://github.com/ruby/ruby.git tmp/ruby
            fi
      - save_cache:
          key: ruby-trunk
          paths:
            - tmp/ruby
  build_image:
    description: "Build Docker image"
    parameters:
      ruby_version:
        type: string
        default: "trunk"
      nightly:
        type: boolean
        default: false
    steps:
      - run:
          name: Build docker image
          command: |
            rake docker:build ruby_version=<< parameters.ruby_version >><<# parameters.nightly >> nightly=yes<</ parameters.nightly >>
  push_image:
    description: "Push Docker image"
    steps:
      - run:
          name: Push docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push rubylang/ruby

jobs:
  build_trunk:
    parameters:
      nightly:
        type: boolean
        default: false
      push:
        type: boolean
        default: false
    docker:
      - image: ruby:latest
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - install_docker_client
      - checkout_ruby_trunk
      - build_image:
          ruby_version: "trunk"
          nightly: << parameters.nightly >>
      - when:
          condition: <<parameters.push>>
          steps:
            - push_image

  build_2_6:
    parameters:
      push:
        type: boolean
        default: false
    docker:
      - image: ruby:latest
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - install_docker_client
      - build_image:
          ruby_version: "2.6.0-preview3"
      - when:
          condition: <<parameters.push>>
          steps:
            - push_image

  build_2_5:
    parameters:
      push:
        type: boolean
        default: false
    docker:
      - image: ruby:latest
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - install_docker_client
      - build_image:
          ruby_version: "2.5.3"
      - when:
          condition: <<parameters.push>>
          steps:
            - push_image

  build_2_4:
    parameters:
      push:
        type: boolean
        default: false
    docker:
      - image: ruby:latest
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - install_docker_client
      - build_image:
          ruby_version: "2.4.5"
      - when:
          condition: <<parameters.push>>
          steps:
            - push_image

  build_2_3:
    parameters:
      push:
        type: boolean
        default: false
    docker:
      - image: ruby:latest
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - install_docker_client
      - build_image:
          ruby_version: "2.3.8"
      - when:
          condition: <<parameters.push>>
          steps:
            - push_image

workflows:
  version: 2

  github:
    jobs:
      - build_trunk:
          push: true
          filters:
            branches:
              only:
                - master
      - build_trunk:
          push: true
          filters:
            branches:
              ignore:
                - master

  nightly:
    triggers:
      - schedule:
          cron: "0 17 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_trunk:
          nightly: true
